---
- hosts: all
  roles:
    - common
    - security

- hosts: controlplane
  roles:
    - role: keepalived
      when: ha_control_plane | default(false) | bool
    - controlplane

- hosts: workers
  roles:
    - worker